# Site settings
title: Encora Apprenticeship Blog
author:
  name: Alfonso Valenciana
  email: alfonso.valenciana@encora.com
description: "A blog documenting my journey through Encora's academy program"

theme: jekyll-theme-time-machine
